<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Asp.NetCore10._0_BigData_Analytics_Project</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\nexa\assets\plugins\.DS_Store" />
    <None Include="wwwroot\nexa\assets\plugins\bootstrap-select\.DS_Store" />
    <None Include="wwwroot\nexa\assets\plugins\summernote\.DS_Store" />
    <None Include="wwwroot\nexa\assets\plugins\tether\.DS_Store" />
    <None Include="wwwroot\nexa\assets\plugins\tether\css\.DS_Store" />
    <None Include="wwwroot\nexa\assets\plugins\tether\js\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="17.14.28" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.14.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.ML.FastTree" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.TimeSeries" Version="5.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\mlmodels\" />
  </ItemGroup>

</Project>
